//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllInOnePlayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\SamplePlaylists\\master.asx")]
        public string MasterPlaylist {
            get {
                return ((string)(this["MasterPlaylist"]));
            }
            set {
                this["MasterPlaylist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int ChannelImageSizeHeight {
            get {
                return ((int)(this["ChannelImageSizeHeight"]));
            }
            set {
                this["ChannelImageSizeHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int ChannelImageSizeWidth {
            get {
                return ((int)(this["ChannelImageSizeWidth"]));
            }
            set {
                this["ChannelImageSizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string NameDefaultPlaylist {
            get {
                return ((string)(this["NameDefaultPlaylist"]));
            }
            set {
                this["NameDefaultPlaylist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("channels")]
        public string NameChannelPlaylist {
            get {
                return ((string)(this["NameChannelPlaylist"]));
            }
            set {
                this["NameChannelPlaylist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("homecontrol")]
        public string NameHomeControlPlaylist {
            get {
                return ((string)(this["NameHomeControlPlaylist"]));
            }
            set {
                this["NameHomeControlPlaylist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int HomeControlImageSizeHeight {
            get {
                return ((int)(this["HomeControlImageSizeHeight"]));
            }
            set {
                this["HomeControlImageSizeHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int HomeControlImageSizeWidth {
            get {
                return ((int)(this["HomeControlImageSizeWidth"]));
            }
            set {
                this["HomeControlImageSizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00000000")]
        public string ChannelImageBackground {
            get {
                return ((string)(this["ChannelImageBackground"]));
            }
            set {
                this["ChannelImageBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public string HomeControlImageBackground {
            get {
                return ((string)(this["HomeControlImageBackground"]));
            }
            set {
                this["HomeControlImageBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Auto")]
        public global::System.Windows.GridLength ColumnSetting0 {
            get {
                return ((global::System.Windows.GridLength)(this["ColumnSetting0"]));
            }
            set {
                this["ColumnSetting0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Auto")]
        public global::System.Windows.GridLength ColumnSetting2 {
            get {
                return ((global::System.Windows.GridLength)(this["ColumnSetting2"]));
            }
            set {
                this["ColumnSetting2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Auto")]
        public global::System.Windows.GridLength RowSetting0 {
            get {
                return ((global::System.Windows.GridLength)(this["RowSetting0"]));
            }
            set {
                this["RowSetting0"] = value;
            }
        }
    }
}
